[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --baud=115200 --chip esp32 --list-all-ports --log-format defmt"

[env]
DEFMT_LOG = "info"

[build]
rustflags = ["-C", "link-arg=-nostartfiles", "-Z", "stack-protector=all"]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
